default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: blogtest_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

test:
  <<: *default
  database: blogtest_test

production:
  <<: *default
  database: blogtest_production
  username: blogtest
  password: <%= ENV["BLOGTEST_DATABASE_PASSWORD"] %>
